[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[lib]
name = "advent_of_code_2024"
path = "src/lib.rs"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
memoize = "0.4.2"
regex = "1.11.1"
